### ISSUE TITLE
Fields in Channel collection type

### ISSUE THREAD

**Issue by kidcessory** [Son923/strapie#5]
Add:
- User (who created or last edited the entry)
- Channel thumbnail
![image](https://user-images.githubusercontent.com/109572118/179682392-4eedbaeb-a161-4a64-8533-1117dbbf6b3d.png)

Modify:
- Categories (pull from YouTube) + add our own categories
- Country: Change country code into full country name

**Comment by kidcessory** [comment]
**User**
Display username of who created/updated the entry on Content Manager view.

**Comment by Son923** [comment]
<img width="1055" alt="image" src="https://user-images.githubusercontent.com/11494525/179972673-4f6642fb-2868-495b-baed-d27dcb403bf6.png">


> Add:
> 
> * User (who created or last edited the entry) - DONE
> * Channel thumbnail - DONE
>   ![image](https://user-images.githubusercontent.com/109572118/179682392-4eedbaeb-a161-4a64-8533-1117dbbf6b3d.png)
> 
> Modify: MOVE TO ISSUE 
> 
> * Categories (pull from YouTube) + add our own categories
> * Country: Change country code into full country name
